# Generated by Django 2.2.7 on 2019-12-04 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='Created_time',
            new_name='created_time',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='Created_time',
            new_name='created_time',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='Created_time',
            new_name='created_time',
        ),
        migrations.AddField(
            model_name='post',
            name='pv',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='post',
            name='uv',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
