# Generated by Django 2.0 on 2019-12-14 06:51

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_content_html'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor.fields.RichTextField(help_text='正文必须为MarkDown格式', verbose_name='正文'),
        ),
    ]
